/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistema.telas;

import br.com.sistema.dal.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.io.IOException; // Será utilizada na classe Exportar

/**
 *
 * @author Rafael Di Bonito
 */
public class TelaCadastroCbo extends javax.swing.JInternalFrame {

    // Usando variavel conexão do dal
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    // Usando a classe ExportarRelatorios e criando a váriavel excel
    ExportarRelatorios excel;

    /**
     * Creates new form TelaCbo
     */
    public TelaCadastroCbo() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    // Criando o método adicionar CBO no banco de dados
    private void adicionar() {
        String sql = "insert into cbo(setor, numero_cbo, funcao_cbo, funcao_empresa)values(?,?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCboSetor.getText());
            pst.setString(2, txtCboNumCbo.getText());
            pst.setString(3, txtCboFuncaoCbo.getText());
            pst.setString(4, txtCboFuncaoEmpresa.getText());

            // Validação dos campos obrigatórios
            if (((txtCboSetor.getText().isEmpty()) || (txtCboNumCbo.getText().isEmpty()) || (txtCboFuncaoCbo.getText().isEmpty()) || (txtCboFuncaoEmpresa.getText().isEmpty()))) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");

            } else {

                // as linha abaixo atualiza a tabela funcionarios com os dados do formulário
                // Também é criado uma estrutura para confirmar a inserção dos dados na tabela 
                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Dados cadastrado com sucesso!");
                    // A linha abaixo chama o método "limpar()"
                    limpar();

                }
            }
            //conexao.close(); //Finaliza a conexão com o banco de dados Mysql
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Criando o método consulta CBO  no banco de dados
    private void pesquisar() {
        String sql = "select id_cbo as ID_CBO, setor as SETOR, numero_cbo as NÚMERO_CBO, funcao_cbo as FUNÇÂO_CBO, funcao_empresa as FUNÇÂO_EMPRESA from cbo where setor like ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCboPesquisar.getText() + "%");
            rs = pst.executeQuery();
            // a linha abaixo usa a biblioteca rs2xml.jar para preencher a tabela cbo
            tabelaCbo.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Criando o método para limpar campos do formulário
    private void limpar() {

        txtCboPesquisar.setText(null);
        txtCboSetor.setText(null);
        txtCboNumCbo.setText(null);
        txtCboFuncaoCbo.setText(null);
        txtCboFuncaoEmpresa.setText(null);
        ((DefaultTableModel) tabelaCbo.getModel()).setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCboSetor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCboFuncaoCbo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCboFuncaoEmpresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCboNumCbo = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCbo = new javax.swing.JTable();
        jLabel38 = new javax.swing.JLabel();
        txtCboPesquisar = new javax.swing.JTextField();
        btnCadastrarCbo = new javax.swing.JButton();
        btnEditarCbo = new javax.swing.JButton();
        btnExcluirCbo = new javax.swing.JButton();
        txtCboId = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Funções CBO");
        setPreferredSize(new java.awt.Dimension(690, 650));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("* Setor");

        txtCboSetor.setMinimumSize(new java.awt.Dimension(100, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("* Número CBO");

        txtCboFuncaoCbo.setMinimumSize(new java.awt.Dimension(100, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("* Função CBO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("* Função Empresa");

        try {
            txtCboNumCbo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("* Campos Obrigatórios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtCboFuncaoCbo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtCboSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(txtCboFuncaoEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txtCboNumCbo, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCboSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCboNumCbo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCboFuncaoCbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCboFuncaoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabelaCbo = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tabelaCbo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SETOR", "NÚMERO CBO", "FUNÇÃO CBO", "FUNÇÃO EMPRESA"
            }
        ));
        tabelaCbo.setFocusable(false);
        tabelaCbo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaCbo);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("Pesquise por Setor ou Função Empresa");

        txtCboPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCboPesquisarKeyReleased(evt);
            }
        });

        btnCadastrarCbo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnCadastrarCbo.setForeground(new java.awt.Color(0, 102, 204));
        btnCadastrarCbo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistema/icones/adicionar.png"))); // NOI18N
        btnCadastrarCbo.setText("Salvar");
        btnCadastrarCbo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCadastrarCbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCboActionPerformed(evt);
            }
        });

        btnEditarCbo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnEditarCbo.setForeground(new java.awt.Color(0, 102, 204));
        btnEditarCbo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistema/icones/editar.png"))); // NOI18N
        btnEditarCbo.setText("Editar");
        btnEditarCbo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditarCbo.setEnabled(false);

        btnExcluirCbo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnExcluirCbo.setForeground(new java.awt.Color(0, 102, 204));
        btnExcluirCbo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistema/icones/excluir.png"))); // NOI18N
        btnExcluirCbo.setText("Excluir");
        btnExcluirCbo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExcluirCbo.setEnabled(false);

        txtCboId.setForeground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(txtCboPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtCboId, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrarCbo)
                .addGap(50, 50, 50)
                .addComponent(btnEditarCbo)
                .addGap(50, 50, 50)
                .addComponent(btnExcluirCbo)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtCboId, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCboPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarCbo)
                    .addComponent(btnExcluirCbo)
                    .addComponent(btnCadastrarCbo))
                .addGap(50, 50, 50))
        );

        setBounds(0, 0, 830, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarCboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCboActionPerformed
        // Chama o método adicionar
        adicionar();
    }//GEN-LAST:event_btnCadastrarCboActionPerformed

    private void txtCboPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCboPesquisarKeyReleased
        // Chama o método pesquisar
        pesquisar();
    }//GEN-LAST:event_txtCboPesquisarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCbo;
    private javax.swing.JButton btnEditarCbo;
    private javax.swing.JButton btnExcluirCbo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCbo;
    private javax.swing.JTextField txtCboFuncaoCbo;
    private javax.swing.JTextField txtCboFuncaoEmpresa;
    private javax.swing.JLabel txtCboId;
    private javax.swing.JFormattedTextField txtCboNumCbo;
    private javax.swing.JTextField txtCboPesquisar;
    private javax.swing.JTextField txtCboSetor;
    // End of variables declaration//GEN-END:variables
}
